DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`(
`id` int(10) NOT NULL AUTO_INCREMENT,
`userName` VARCHAR (20) DEFAULT NULL ,
`password` VARCHAR (20) DEFAULT NULL ,
`name` VARCHAR (20) DEFAULT NULL ,
`idNumber` VARCHAR (20) DEFAULT NULL ,
`department` VARCHAR (20) DEFAULT NULL ,
`position` VARCHAR (20) DEFAULT NULL,
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8;